### ISSUE TITLE
Qual foi sua motivação para adicionar essa instrução?

### ISSUE THREAD

**Issue by edysegura** [EderGuima/sw-universe#2]
https://github.com/EderGuima/sw-universe/blob/3b514c6fc36cf5d8e1ab7f8a7c4864dd849fd777/sw/js/inicial.js#L1

**Comment by EderGuima** [comment]
Bom dia Edy!!
Eu estou fazendo um curso de NodeJs que ensina a usar o Yarn, e pelo Yarn eu conheci o Babel, que transcreve as instruções js para ficar compatível com versões mais antigas de js. Para ser sincero, eu não sabia o que essa instrução fazia, pesquisei e entendi que o 'use strict' não permite usar variáveis que não foram declaradas e como é compatível com todos os navegadores eu mantive ele no código.

**Comment by edysegura** [comment]
Obrigado pelo retorno @EderGuima
